version: "3.3"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 127.0.0.1:5432:5432
  parser:
    build: .
    environment:
      DB_URI: '${DB_URI}'
    restart: always
    depends_on:
      - db
    logging:
      options:
        max-size: 1m